<?php
return array(
    'global_xss_filtering' => True,
    'merchant_scale_status' => array(
        MP_INIT => array('name' => '初始'),
        MP_EFFECT => array('name' => '生效'),
        MP_LOCK => array('name' => '失效'),
        MP_STOP => array('name' => '失效'),
    ),
    'shop_logo_url'=>'http://img4.ddimg.cn/00253/1/logo.jpg',
    //联盟荐书相关配置
    'allianceType' => array(
        'recommendBooks' =>32,
    ),
    'allianceDepartment' => array(
        'wireless' => 2,
        'online' => 1,
    ),
);
